<?xml version="1.0" encoding="UTF-8"?>
<ArcPad>
   <LAYER name="Feeder_Protein">
      <SYMBOLOGY>
         <SIMPLELABELRENDERER visible="true" field="FEEDER">
            <TEXTSYMBOL angle="0" fontcolor="255,255,0" font="Arial" fontstyle="bold" fontsize="14" horzalignment="left" vertalignment="bottom" rtl="false">
            </TEXTSYMBOL>
         </SIMPLELABELRENDERER>
         <SIMPLERENDERER label="">
            <GROUPSYMBOL>
               <TRUETYPEMARKERSYMBOL font="ESRI Default Marker" character="70" fontcolor="0,0,0" fontsize="11" angle="0">
               </TRUETYPEMARKERSYMBOL>
               <TRUETYPEMARKERSYMBOL font="ESRI Default Marker" character="71" fontcolor="255,255,0" fontsize="11" angle="0">
               </TRUETYPEMARKERSYMBOL>
            </GROUPSYMBOL>
         </SIMPLERENDERER>
      </SYMBOLOGY>
   </LAYER>
</ArcPad>
